In [6]:
import tensorflow as tf

In [7]:
mnist= tf.keras.datasets.mnist

(x_train,y_train),(x_test, y_test)= mnist.load_data()


In [8]:
x_train.shape

(60000, 28, 28)

In [9]:
y_train.shape

(60000,)

In [10]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [11]:
x_train, x_test = x_train/255.0, x_test/255.0

In [12]:
x_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input,Dropout, Flatten

model= Sequential()
model.add(Input((28,28)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10))

In [29]:
nonsense= model(x_train[:1]).numpy()
nonsense

array([[-0.6042144 ,  0.17273103,  0.27114594, -0.33567652, -0.26679617,
         0.637411  , -0.18448493, -0.59407175, -0.17117289, -0.48678127]],
      dtype=float32)

In [30]:
tf.nn.softmax(nonsense).numpy()

array([[0.05901982, 0.12835743, 0.14163221, 0.0772009 , 0.08270594,
        0.20428145, 0.08980159, 0.05962148, 0.09100503, 0.06637408]],
      dtype=float32)

In [31]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
loss_fn= SparseCategoricalCrossentropy(from_logits=True)

loss_fn(y_train[:1], nonsense)

<tf.Tensor: shape=(), dtype=float32, numpy=1.588256597518921>

In [32]:
from tensorflow.keras.optimizers import Adam

optimizer= Adam(learning_rate= 0.01)

model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])

In [35]:
model.fit(x_train,y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9547 - loss: 0.1833
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9551 - loss: 0.1814
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9571 - loss: 0.1802
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9577 - loss: 0.1714
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9586 - loss: 0.1680
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9592 - loss: 0.1687
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9615 - loss: 0.1646
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9618 - loss: 0.1647
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9610 - loss: 0.1738
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9606 - loss: 0.1690


In [34]:
model.evaluate(x_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9645 - loss: 0.2158


[0.2158043384552002, 0.9645000100135803]

In [37]:
tf.argmax(tf.nn.softmax(model(x_test[:1])).numpy(), axis=1)

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([7])>

In [41]:
y_test[:1]

array([7], dtype=uint8)